/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRoles;

import Business.EcoSystem;
import UserInterface.ManageEnterpriseAdminJPanel_2;
import UserInterface.ManageEnterpriseJPanel_2;
import UserInterface.ManageNetworkJPanel_2;
import UserInterface.ManageNetworkJPanel_2;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class SystemAdminPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminPanelForm
     */
   JPanel container;
   EcoSystem system;
    public SystemAdminPanelForm() {
        initComponents();
    }

    public SystemAdminPanelForm(JPanel userProcessContainer, EcoSystem system) {
       initComponents();
    
        this.container = userProcessContainer;
        this.system = system;
// throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageNetwork = new javax.swing.JButton();
        manageAdmin = new javax.swing.JButton();
        manageEnterprise = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageNetwork.setBackground(new java.awt.Color(0, 153, 153));
        manageNetwork.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        manageNetwork.setText("Manage State Network");
        manageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkActionPerformed(evt);
            }
        });
        add(manageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 530, 60));

        manageAdmin.setBackground(new java.awt.Color(0, 153, 153));
        manageAdmin.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        manageAdmin.setText("Manage Enterprise Admin");
        manageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminActionPerformed(evt);
            }
        });
        add(manageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 530, 60));

        manageEnterprise.setBackground(new java.awt.Color(0, 153, 153));
        manageEnterprise.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        manageEnterprise.setText("Manage Enterprise");
        manageEnterprise.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        manageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseActionPerformed(evt);
            }
        });
        add(manageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 530, 60));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("System Admin Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 440, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/crop-imagecopy2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1710, 930));
    }// </editor-fold>//GEN-END:initComponents
    private void manageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminActionPerformed
        // TODO add your handling code here:
                ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(container, system);
        container.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageAdminActionPerformed

    private void manageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel_2 manageNetworkJPanel = new  ManageNetworkJPanel_2(container, system);
        container.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageNetworkActionPerformed

    private void manageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(container, system);
        container.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAdmin;
    private javax.swing.JButton manageEnterprise;
    private javax.swing.JButton manageNetwork;
    // End of variables declaration//GEN-END:variables
}
