/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRolePanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.FarmerData.HealthData;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthReportRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class FarmerDocRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmerDetailInformation
     */
    private JPanel container;
    private UserAccount account;
    private Organization org;
    private Enterprise ent; 
    private Network network;
    private EcoSystem system;
    
//    public FarmerDocRequestPanel() {
//        initComponents();
//    }

    FarmerDocRequestPanel(JPanel userProcessContainer, UserAccount account, Organization org, Enterprise ent,Network network, EcoSystem system) {
        initComponents();
        this.container  = userProcessContainer;
        this.account = account;
        this.org = org;
        this.ent = ent;
        this.network = network;
        this.system = system;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorReqTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        messageTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sendReqBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultation to Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 550, 60));

        doctorReqTable.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        doctorReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Status", "FeedBack", "Date"
            }
        ));
        jScrollPane1.setViewportView(doctorReqTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 920, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doctor Request History :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 830, 40));

        backBtn.setBackground(new java.awt.Color(0, 153, 153));
        backBtn.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 830, 260, 60));

        messageTxt.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        add(messageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 600, 90));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Please  enter the information which you wanted to request");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 620, 40));

        sendReqBtn.setBackground(new java.awt.Color(0, 153, 153));
        sendReqBtn.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        sendReqBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendReqBtn.setText("Send");
        sendReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReqBtnActionPerformed(evt);
            }
        });
        add(sendReqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 840, 260, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/crop-imagecopy2.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 930));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void sendReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReqBtnActionPerformed
        // TODO add your handling code here:
        String message = messageTxt.getText().trim();
        HealthReportRequest hrr = new HealthReportRequest();
        if(!message.isEmpty()){
            
            hrr.setSender(account);
            hrr.setStatus("Waiting");
            hrr.setMessage(message);
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter message", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        Enterprise ent1 = null;
        
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise instanceof HospitalEnterprise){
                ent1 = enterprise;
                break;
            }
        }
        
        for(Organization organization : ent1.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof DoctorOrganization){
                organization.getWorkQueue().getWorkRequestList().add(hrr);
                account.getWorkQueueDoc().getWorkRequestList().add(hrr);
            }
        }
        
        populateTable();
        
    }//GEN-LAST:event_sendReqBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable doctorReqTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageTxt;
    private javax.swing.JButton sendReqBtn;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel)doctorReqTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[4];
        for(WorkRequest req : account.getWorkQueueDoc().getWorkRequestList()){
                    row[0] = req.getMessage();
                    row[1] = req;
                    row[2] = req.getResponse();
                    row[3] = req.getRequestDate();
                    model.addRow(row);
        }
        
        
        
    }
}
